### ISSUE TITLE
Liberar dispositivo

### ISSUE THREAD

**Issue by mmedina94** [mmedina94/BiosSecurity#6]
Hay que analizar los casos de uso y en base a eso hacer las funcionalidades.
Hay funcionalidades como dar de alta un servicio que implica tener un cliente y tener una propiedad en estos casos hacer transacciones.

Viejo fijate el tema de liberar dispositivo a nivel de BD

![image](https://user-images.githubusercontent.com/23190304/27506308-dd9ac6e4-588b-11e7-8708-f91f0e183257.png)

**Comment by mmedina94** [comment]
Dispositivo se borra si no esta asociado a un servicio

**Comment by aalbornoz** [comment]
Se corrigieron casos de uso, Dispositivo se borra por un administrativo si no esta asociado a un servicio, y por un técnico se libera nulleando el campo servicio del dispositivo.
